### ISSUE TITLE
Download / how to build?

### ISSUE THREAD

**Issue by mkvalsvik** [jrtc27/Airmac#1]
Hi I'm a developer but not a Mac developer.  What's the best/fastest way to build this thing?

Hoping to get it to work on a Mac mini with Lion.

Thanks for taking the time to improve on it.

**Comment by futurekill** [comment]
Install Xcode - http://itunes.apple.com/us/app/xcode/id497799835?mt=12
Clone the repo
Double click on the Airmac.xcodeproj file and Xcode should start up and open the project.
You can then hit the play button or click Product in the menu bar and then Build.

**Comment by jrtc27** [comment]
What @futurekill said. I will upload some pre-built binaries soon as well.

**Comment by jrtc27** [comment]
I never got round to this, but GitHub doesn't have a downloads feature any more. Closing.
