### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by victorzimmer** [jrtc27/Airmac#2]
Whatsup with IPv6?
It could not bind to IPv6 address???

**Comment by jrtc27** [comment]
What version of OS X are you on?

**Comment by victorzimmer** [comment]
I'm on Mac OS X 10.7.3 trying to stream from a iOS device using iOS 5.1.1 (9B206)

**Comment by jrtc27** [comment]
Seems strange. Have you got anything else running that could interfere?

**Comment by victorzimmer** [comment]
Not that I know. Just force quitted netbiosd (not supposed to be done LOL) and it works…
Server started successfully. It doesn't show up on the iPhone tough…

**Comment by jrtc27** [comment]
Closing this as it's been 9 months. If you're still having issues, please reopen this, but otherwise I'll assume that the issue's resolved.
