### ISSUE TITLE
3rd Party Airplay Apps not connecting.

### ISSUE THREAD

**Issue by Otoris** [jrtc27/Airmac#3]
I'm trying to get Djay, Pandora Radio and Soundcloud to stream music to my Macbook Pro. (2010 if it matters) None of these apps want to start streaming their content to my Mac though. Streaming video and music from the "Music" app works like a charm. Streaming video from Crunchyroll works fine too. (3rd Party Video streaming app)

Any suggestions on how I can debug this or get it to work? Thanks in advance!

**Comment by Otoris** [comment]
Running iOS 5.0.1 with iPhone 4S, jailbroken.

**Comment by jrtc27** [comment]
Streaming music is currently unsupported (it uses a different protocol to photos and videos), so I'm surprised you got music to work.

**Comment by Otoris** [comment]
Hah! So, I tested video streaming from the music app first, then while still connected with airplay and paused in the video, I browsed to a song and hit play and it works fine. 

Starting the music app and playing music via Airplay though refuses to work without first having started a video.

**Comment by jrtc27** [comment]
Interesting - it must be that music hooks into the other protocol if it's connected already (there's no reason why that protocol can't support music, it's just Apple wants to encrypt it).

**Comment by therealcmj** [comment]
I understand that AirMac doesn't currently support the apps other than "Video". What are the chances of extending it to support generic screen cloning a la AirServer or Reflection.app?

**Comment by jrtc27** [comment]
It's encrypted, and reverse-engineering the protocol (which is what they did) is hellish., so unless someone makes it public I doubt I'll be able to get it to work.

**Comment by jrtc27** [comment]
Marking as resolved.
